version: "3"
services:
  backend:
    image: fast_api_app
    #container_name: backend
    volumes:
      - ./fast_api:/src
    ports:
      - "8000:8000"

  frontend:
    image: streamlit
    #container_name: frontend
    volumes:
      - ./streamlit:/src
    ports:
      - "8001:8001"

# docker compose automáticamente nos crea una red que conecta a los dos containers, 
# accediendo por su nombre como host